"""Write the five per-flavour .toc files from Manners.toc.

    python tools/maketocs.py           # write them
    python tools/maketocs.py --check   # say whether they are up to date

The game reads Manners_<Flavour>.toc in preference to Manners.toc, so shipping
real per-flavour files is what lets one addon declare the right interface number
on each of the five live clients. They differ in exactly one line, which is why
they are generated: five hand-maintained copies of the same file list drift, and
the way a toc drift shows up is that one client silently loads four files
instead of five and the addon is dead there with no message.

Manners.toc stays in the tree as the one file anybody edits, and as the fallback
for a client that does not honour a suffixed name. tests/validate.py re-runs the
render in memory and fails if the result differs from what is on disk, so a hand
edit to a generated file cannot survive a test run unnoticed.

Named without a hyphen, unlike its neighbours, because tests/validate.py imports
it -- a module with a hyphen in its name cannot be imported at all.
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = "Manners.toc"

# suffix -> the interface number that client reports, September 2026.
#
# Cataclysm Classic is absent because it is retired; Season of Discovery and
# Hardcore are absent because they are Classic Era and not separate clients.
FLAVOURS = [
    ("Mainline", 120100),   # retail "Midnight" 12.1
    ("Camelot", 16001),     # WoW Forever 1.60.1
    ("Mists", 50504),       # Mists of Pandaria Classic
    ("TBC", 20506),         # Burning Crusade Classic Anniversary
    ("Vanilla", 11509),     # Classic Era 1.15.9
]

BANNER = ("# Generated by tools/maketocs.py from %s -- do not edit by hand.\n"
          "# %s client. Everything but the interface number comes from %s.\n")


def body(template):
    """The template from its first directive on, with the Interface line gone.

    Dropping everything above the first "## " throws away Manners.toc's own
    explanation of why it exists, which is true of that file and not of these.
    """
    lines = template.splitlines(True)
    start = next((i for i, l in enumerate(lines) if l.startswith("## ")), 0)
    return "".join(l for l in lines[start:] if not l.startswith("## Interface:"))


def render(template, suffix, interface):
    return "%s## Interface: %d\n%s" % (
        BANNER % (SOURCE, suffix, SOURCE), interface, body(template))


def expected():
    """{filename: the exact bytes that file should hold}."""
    template = open(os.path.join(ROOT, SOURCE), encoding="utf-8").read()
    return {"Manners_%s.toc" % suffix: render(template, suffix, interface)
            for suffix, interface in FLAVOURS}


def main(check):
    stale = []
    for name, want in expected().items():
        path = os.path.join(ROOT, name)
        have = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if have == want:
            print("  ok       %s" % name)
            continue
        stale.append(name)
        if check:
            print("  STALE    %s -- run python tools/maketocs.py" % name)
        else:
            # newline="\n" because the game's toc parser is read on Windows as
            # often as not, and .gitattributes pins every toc in this tree to LF.
            open(path, "w", encoding="utf-8", newline="\n").write(want)
            print("  written  %s" % name)
    return 1 if (check and stale) else 0


if __name__ == "__main__":
    sys.exit(main("--check" in sys.argv[1:]))
