"""Write the per-flavour .toc files from Manners.toc.

    python tools/maketocs.py           # write them
    python tools/maketocs.py --check   # say whether they are up to date

The game reads Manners_<Flavour>.toc in preference to Manners.toc, so shipping
real per-flavour files is what lets one addon declare the right interface number
on each client it supports. 1.0 supports one, so FLAVOURS below has one entry
and this writes one file, Manners_Camelot.toc; the others are commented out
until somebody runs the addon on them.

STAGED below is the step between: a flavour whose toc is written, kept up to
date and checked like the shipped ones, but into tools/tocs/ rather than beside
Manners.toc. That is where it does not ship. The BigWigs packager finds every
Manners_<Flavour>.toc in the checkout's top folder -- not in the zip it builds,
the checkout -- and tags the CurseForge and Wago upload with each one's game
version, so a staged toc at the top level would publish the addon for that
client on the next tag even if .pkgmeta kept the file itself out of the zip.
tools/ is in .pkgmeta's ignore list, and the packager never looks inside it.
A tester copies the staged file next to Manners.toc in their own AddOns folder. Each generated toc differs from the
source in exactly one line, which is why they are generated: hand-maintained
copies of the same file list drift, and the way a toc drift shows up is that a
client silently loads four files instead of five and the addon is dead there
with no message.

Manners.toc stays in the tree as the one file anybody edits, and as the fallback
for a client that does not honour a suffixed name. tests/validate.py re-runs the
render in memory and fails if the result differs from what is on disk, so a hand
edit to a generated file cannot survive a test run unnoticed.

Named without a hyphen, unlike its neighbours, because tests/validate.py imports
it -- a module with a hyphen in its name cannot be imported at all.
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = "Manners.toc"

# suffix -> the interface number that client reports, September 2026.
#
# Cataclysm Classic is absent because it is retired; Season of Discovery and
# Hardcore are absent because they are Classic Era and not separate clients.
# Every live client ships since 1.7.0. Each set of spell ids was checked
# against that client's own data (wago.tools DB2 of its build), and each has a
# scenario file of its own (tests/scenarios/<flavour>.lua).
FLAVOURS = [
    ("Camelot", 16001),     # WoW Forever 1.60.1
    ("Vanilla", 11509),     # Classic Era 1.15.9 -- since 1.6.7
    ("TBC", 20506),         # Burning Crusade Classic Anniversary 2.5.6
    ("Mists", 50504),       # Mists of Pandaria Classic 5.5.4
    ("Mainline", 120100),   # retail "Midnight" 12.1.0
]

# Written, but not where the packager or the game looks (see the docstring).
# Empty since every client ships; a flavour goes here when it is implemented
# but not yet ready to publish.
STAGED = [
]
STAGED_DIR = os.path.join("tools", "tocs")

BANNER = ("# Generated by tools/maketocs.py from %s -- do not edit by hand.\n"
          "# %s client. Everything but the interface number comes from %s.\n")


def body(template):
    """The template from its first directive on, with the Interface line gone.

    Dropping everything above the first "## " throws away Manners.toc's own
    explanation of why it exists, which is true of that file and not of these.
    """
    lines = template.splitlines(True)
    start = next((i for i, l in enumerate(lines) if l.startswith("## ")), 0)
    return "".join(l for l in lines[start:] if not l.startswith("## Interface:"))


def render(template, suffix, interface):
    return "%s## Interface: %d\n%s" % (
        BANNER % (SOURCE, suffix, SOURCE), interface, body(template))


def expected():
    """{path from the addon folder: the exact bytes that file should hold}.

    The shipped tocs by bare name, the staged ones under STAGED_DIR, with
    forward slashes either way.
    """
    template = open(os.path.join(ROOT, SOURCE), encoding="utf-8").read()
    out = {"Manners_%s.toc" % suffix: render(template, suffix, interface)
           for suffix, interface in FLAVOURS}
    staged = STAGED_DIR.replace(os.sep, "/")
    for suffix, interface in STAGED:
        out["%s/Manners_%s.toc" % (staged, suffix)] = render(template, suffix, interface)
    return out


def main(check):
    stale = []
    for name, want in expected().items():
        path = os.path.join(ROOT, name)
        have = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if have == want:
            print("  ok       %s" % name)
            continue
        stale.append(name)
        if check:
            print("  STALE    %s -- run python tools/maketocs.py" % name)
        else:
            # newline="\n" because the game's toc parser is read on Windows as
            # often as not, and .gitattributes pins every toc in this tree to LF.
            os.makedirs(os.path.dirname(path), exist_ok=True)
            open(path, "w", encoding="utf-8", newline="\n").write(want)
            print("  written  %s" % name)
    return 1 if (check and stale) else 0


if __name__ == "__main__":
    sys.exit(main("--check" in sys.argv[1:]))
